// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type OptionsLegacyParser } from '@hey-api/client-fetch';
import type { ReadRootGetError, ReadRootGetResponse, ReadItemItemsItemIdGetData, ReadItemItemsItemIdGetError, ReadItemItemsItemIdGetResponse, ReadOrdersOrdersGetError, ReadOrdersOrdersGetResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * Read Root
 */
export const readRootGet = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<ReadRootGetResponse, ReadRootGetError, ThrowOnError>({
        ...options,
        url: '/'
    });
};

/**
 * Read Item
 */
export const readItemItemsItemIdGet = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<ReadItemItemsItemIdGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<ReadItemItemsItemIdGetResponse, ReadItemItemsItemIdGetError, ThrowOnError>({
        ...options,
        url: '/items/{item_id}'
    });
};

/**
 * Read Orders
 */
export const readOrdersOrdersGet = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<ReadOrdersOrdersGetResponse, ReadOrdersOrdersGetError, ThrowOnError>({
        ...options,
        url: '/orders/'
    });
};