// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type OptionsLegacyParser } from '@hey-api/client-fetch';
import type { DefaultReadOrdersError, DefaultReadOrdersResponse, DefaultAddRandomOrderError, DefaultAddRandomOrderResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * Read Orders
 */
export const defaultReadOrders = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<DefaultReadOrdersResponse, DefaultReadOrdersError, ThrowOnError>({
        ...options,
        url: '/orders/'
    });
};

/**
 * Add Random Order
 * Add an order with completely random data.
 */
export const defaultAddRandomOrder = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
    return (options?.client ?? client).post<DefaultAddRandomOrderResponse, DefaultAddRandomOrderError, ThrowOnError>({
        ...options,
        url: '/orders/random'
    });
};