// This file is auto-generated by @hey-api/openapi-ts

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Order = {
    orderId: string;
    customerName: string;
    status: OrderStatus;
    timestamp: string;
    amount: number;
    paymentStatus: PaymentStatus;
    shippingAddress: string;
};

export type OrderStatus = 'Pending' | 'Shipped' | 'Delivered' | 'Default';

export type PaymentStatus = 'Paid' | 'Pending' | 'Failed' | 'Default';

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type ReadRootGetResponse = (unknown);

export type ReadRootGetError = unknown;

export type ReadItemItemsItemIdGetData = {
    path: {
        item_id: number;
    };
    query?: {
        q?: (string | null);
    };
};

export type ReadItemItemsItemIdGetResponse = (unknown);

export type ReadItemItemsItemIdGetError = (HTTPValidationError);

export type ReadOrdersOrdersGetResponse = (Array<Order>);

export type ReadOrdersOrdersGetError = unknown;