// This file is auto-generated by @hey-api/openapi-ts

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type ReadRootGetResponse = (unknown);

export type ReadRootGetError = unknown;

export type ReadItemItemsItemIdGetData = {
    path: {
        item_id: number;
    };
    query?: {
        q?: (string | null);
    };
};

export type ReadItemItemsItemIdGetResponse = (unknown);

export type ReadItemItemsItemIdGetError = (HTTPValidationError);