// This file is auto-generated by @hey-api/openapi-ts

export type Customer = {
    id: string;
    name: string;
    email: string;
    password: string;
    address: string;
    created: (string | null);
    updated: (string | null);
    deleted?: boolean;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Order = {
    id: string;
    productId: string;
    customerId: string;
    status?: OrderStatus;
    quantity: number;
    paymentStatus?: PaymentStatus;
    created: (string | null);
    updated: (string | null);
    deleted?: boolean;
};

export type OrderStatus = 'Pending' | 'Shipped' | 'Delivered';

export type PaginatedCustomersResponse = {
    total: number;
    page: number;
    size: number;
    results: Array<Customer>;
};

export type PaginatedOrdersResponse = {
    total: number;
    page: number;
    size: number;
    results: Array<Order>;
};

export type PaginatedProductsResponse = {
    total: number;
    page: number;
    size: number;
    results: Array<Product>;
};

export type PaymentStatus = 'Paid' | 'Pending' | 'Failed';

export type Product = {
    id: string;
    name: string;
    description: string;
    price: number;
    quantity: number;
    created: (string | null);
    updated: (string | null);
    deleted?: boolean;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type DefaultHealthCheckResponse = (unknown);

export type DefaultHealthCheckError = unknown;

export type DefaultReadOrdersData = {
    query?: {
        page?: number;
        size?: number;
    };
};

export type DefaultReadOrdersResponse = (PaginatedOrdersResponse);

export type DefaultReadOrdersError = (HTTPValidationError);

export type DefaultReadProductsData = {
    query?: {
        page?: number;
        size?: number;
    };
};

export type DefaultReadProductsResponse = (PaginatedProductsResponse);

export type DefaultReadProductsError = (HTTPValidationError);

export type DefaultReadCustomersData = {
    query?: {
        page?: number;
        size?: number;
    };
};

export type DefaultReadCustomersResponse = (PaginatedCustomersResponse);

export type DefaultReadCustomersError = (HTTPValidationError);

export type DefaultAddRandomOrderResponse = (Order);

export type DefaultAddRandomOrderError = unknown;

export type DefaultAddRandomCustomerResponse = (Customer);

export type DefaultAddRandomCustomerError = unknown;

export type DefaultAddRandomProductResponse = (Product);

export type DefaultAddRandomProductError = unknown;

export type DefaultRestockProductsResponse = (Array<Product>);

export type DefaultRestockProductsError = unknown;

export type DefaultUpdateRandomOrderStatusResponse = (unknown);

export type DefaultUpdateRandomOrderStatusError = unknown;

export type DefaultUpdatePaymentStatusResponse = (unknown);

export type DefaultUpdatePaymentStatusError = unknown;